[settings]
pin = true
experimental = true

[settings.npm]
bun = true

[tools]
cosign = "3.0.4"
bun = "1.3.9"
deno = "2.6.9"
go = "1.26.0"
java = [
  "temurin-25.0.2+10.0.LTS",
  "zulu-24.30.11.0"
]
node = "24.13.1"
# renovate: datasource=npm depName=npm
npm = "11.9.0"
pnpm = "10.29.3"
# renovate: datasource=github-tags depName=slsa-framework/slsa-verifier versioning=semver
slsa-verifier = "2.7.1"
usage = "2.16.2"
"aqua:yarnpkg/berry" = "4.11.0"
rust = "1.93.1"
# renovate: datasource=npm depName=@openai/codex
codex = "0.98.0"
jq = "1.8.1"
eza = "0.22.0"
awscli = "2.33.22"
kubectl = "1.35.1"
terraform = "1.14.5"

[hooks]
postinstall = '''
MISE_DATA_ROOT="${MISE_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/mise}"

for version_dir in "$MISE_DATA_ROOT"/installs/node/*; do
  [[ -d "$version_dir" ]] || continue
  [[ -L "$version_dir" ]] && continue

  version=$(basename $version_dir)
  bin_dir="$version_dir/bin"
  [[ -d "$bin_dir" ]] || continue

  removed_any=false

  for base in npm npx corepack; do
    f="$bin_dir/$base"
    [[ -e "$f" ]] || continue

    rm -f -- "$f"
    echo "ðŸ—‘ï¸ Stripping $base from node version $version"
  done
done

mise reshim node >/dev/null
'''
