[settings]
pin = true
experimental = true

[settings.npm]
bun = true

[tools]
cosign = "3.0.2"
bun = "1.3.3"
deno = "2.5.6"
go = "1.25.4"
java = [
  "temurin-25.0.1+8.0.LTS",
  "zulu-24.30.11.0"
]
node = "24.11.1"
# renovate: datasource=npm depName=npm
npm = "11.6.3"
pnpm = "10.23.0"
# renovate: datasource=github-tags depName=slsa-framework/slsa-verifier versioning=semver
slsa-verifier = "2.7.1"
usage = "2.8.0"
"aqua:yarnpkg/berry" = "4.11.0"
rust = "1.91.1"
# renovate: datasource=npm depName=@openai/codex
codex = "0.63.0"
jq = "1.8.1"
eza = "0.22.0"
awscli = "2.32.4"
kubectl = "1.34.2"
terraform = "1.14.0"

[hooks]
postinstall = '''
MISE_DATA_ROOT="${MISE_DATA_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/mise}"

for version_dir in "$MISE_DATA_ROOT"/installs/node/*; do
  [[ -d "$version_dir" ]] || continue
  [[ -L "$version_dir" ]] && continue

  version=$(basename $version_dir)
  bin_dir="$version_dir/bin"
  [[ -d "$bin_dir" ]] || continue

  removed_any=false

  for base in npm npx corepack; do
    f="$bin_dir/$base"
    [[ -e "$f" ]] || continue

    rm -f -- "$f"
    echo "ðŸ—‘ï¸ Stripping $base from node version $version"
  done
done

mise reshim node >/dev/null
'''
