name: verify-mise-install

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - system_files/etc/mise/config.toml
      - .github/workflows/mise-install.yml

jobs:
  mise-install:
    name: Validate mise install
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3
        with:
          cache: true

      - name: Install devbox toolchain
        env:
          MISE_CONFIG_FILE: system_files/etc/mise/config.toml
          MISE_EXPERIMENTAL: 1
          MISE_YES: 1
        run: mise install
