name: verify-mise-install

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - system_files/etc/mise/config.toml
      - .github/workflows/mise-install.yml

jobs:
  mise-install:
    name: Validate mise install
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6

      - name: Set up mise
        uses: jdx/mise-action@146a28175021df8ca24f8ee1828cc2a60f980bd5 # v3
        with:
          cache: true

      - name: Install devbox toolchain
        env:
          MISE_CONFIG_FILE: system_files/etc/mise/config.toml
          MISE_EXPERIMENTAL: 1
          MISE_YES: 1
        run: mise install
